export enum InvitationSections {
  groomName = "Nombre del novio",
  brideName = "Nombre de la novia",
  eventDate = "Fecha del evento",
  welcomeMessage = "Mensaje de bienvenida",
  bibleVerse = "Versículo de la biblia",
  groomParents = "Papás del novio",
  brideParents = "Papás de la novia",
  guestMessage = "Mensaje al invitado",
  dressCode = "Código de vestimenta",
  specialRequest = "Petición especial",
  itinerary = "Itinerario",
  giftTable = "Mesa de regalos",
  recomendedLodging = "Hospedaje recomendado",
}
