export const invitationSetupInitialValues = {
  brideName: "",
  groomName: "",
  primaryColor: "#000000",
  secondaryColor: "#000000",
  eventDate: "",
  welcomeMessage: "",
  bibleVerse: "",
  bibleReference: "",
  brideParents: "",
  groomParents: "",
  guestMessage: "",
  dressCode: "",
  specialRequest: "",
  itinerary: [
    {
      eventType: "",
      eventTime: "",
      eventLocation: "",
      eventAddress: "",
      eventAddressLink: "",
    },
  ],
  giftRegistryType: "",
  giftRegistryLink: "",
  giftRegistryMsg: "",
  brideImage: undefined,
  eventDateImage: undefined,
  bibleImage: undefined,
  specialRequestImage: undefined,
};
